# Configuração do golangci-lint para Bagus Browser
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    
  disable:
    - deadcode
    - structcheck
    - varcheck

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    
  gofmt:
    simplify: true
    
  revive:
    confidence: 0.8

issues:
  # Ignora erros de import de webview (CGO)
  exclude:
    - "could not import github.com/webview/webview_go"
    - "Package gtk\\+-3\\.0 was not found"
    - "Package 'webkit2gtk-4\\.0'"
    
  # Não reporta typecheck em pacotes CGO
  exclude-rules:
    - path: main.go
      linters:
        - typecheck
    - path: cmd/bagus/main.go
      linters:
        - typecheck
    - path: internal/ui/
      linters:
        - typecheck
    
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
