# Configuração do golangci-lint para Bagus Browser
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    
  disable:
    - typecheck  # Desabilitado: requer GTK/WebKit no CI

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    
  gofmt:
    simplify: true
    
  revive:
    confidence: 0.8

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
